- name: dir setup
  import_playbook: playbooks/yaml-examples/logs-setup.yaml


- name: commander setup
  import_playbook: playbooks/yaml-examples/commander-setup.yaml


- name: ships setup
  import_playbook: playbooks/yaml-examples/ships-setup.yaml


- name: read commander logs 
  import_playbook: playbooks/yaml-examples/read-commander-logs.yaml


- name: read ships logs 
  import_playbook: playbooks/yaml-examples/read-ships-logs.yaml


- name: commander command
  import_playbook: playbooks/yaml-examples/commander-command.yaml
  vars:
    tool: "cat"
    parameter: "/target_logs/{{inventory_hostname}}-commander.txt"