- name: dir setup
  run_once: true
  import_playbook: playbooks/yaml-examples/setup/logs-setup.yaml

- name: commander setup
  run_once: true
  import_playbook: playbooks/yaml-examples/setup/commander-setup.yaml

- name: ships setup
  run_once: true
  import_playbook: playbooks/yaml-examples/setup/ships-setup.yaml

- name: commander command
  import_playbook: playbooks/yaml-examples/commands/commander-command.yaml
  vars:
    tool: "ls"
    parameter: "-la"

- name: ships get random pokemon
  import_playbook: playbooks/yaml-examples/commands/ships-pokemon-command.yaml

- name: read commander logs 
  import_playbook: playbooks/yaml-examples/logs/read-commander-logs.yaml

- name: read ships logs 
  import_playbook: playbooks/yaml-examples/logs/read-ships-logs.yaml
- 
  name: logging completion of playbook...
  hosts: [commanders]
  tasks:
    - include_tasks: playbooks/yaml-examples/logs/write-commander-logs.yaml
      vars:
        event: "playbook complete"
        event_result: " 🙌 finished without breaking 💯..."
- 
  name: logging completion of playbook...
  hosts: [ships]
  tasks:
    - include_tasks: playbooks/yaml-examples/logs/write-ships-logs.yaml
      vars:
        event: "playbook complete"
        event_result: "👏 finished without breaking 😤..."
