- 
  name: CHecking Enviroment Variables
  hosts: all
  tasks:
    - name: Checking if DIR_SETUP is set
      ansible.builtin.debug:
        msg: "DIR_SETUP: {{ lookup('ansible.builtin.env', 'DIR_SETUP') }}"

    - name: Checking if COMMANDER_SETUP is set
      ansible.builtin.debug:
        msg: "COMMANDER_SETUP: {{ lookup('ansible.builtin.env', 'COMMANDER_SETUP') }}"

    - name: CHecking if SHIPS_SETUP is set
      ansible.builtin.debug:
        msg: "host: {{ansible_hostname}} ,SHIPS_SETUP: {{ lookup('ansible.builtin.env', 'SHIPS_SETUP') }}"

- name: setup
  import_playbook: playbooks/yaml-examples/setup-playbook.yaml

- name: logging
  import_playbook: playbooks/yaml-examples/log-playbook.yaml
  when: DIR_SETUP==1

- name: commander nslookup
  import_playbook: playbooks/yaml-examples/commander-nslookup.yaml
  when: COMMANDER_SETUP==1
