version: '3.9'

services:
  target: &target
    image: target
    tty: true   
    scale: 4
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - target_logs:/target_logs

volumes:
  target_logs: {}