version: '3.9'

services:
  target: &target
    tty: true   
    scale: 4
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - target_logs:/target_logs

  controller: 
    <<: *target
    scale: 1
    volumes:
      - target_logs:/target_logs
volumes:
  target_logs: {}