-
  name: commanders setup 
  hosts: commanders
  tags: ['commander', 'setup']
  vars:
    log_dir: "/target_logs"
    file_name: "{{inventory_hostname}}-commander.txt"
  tasks:
    - name: create commander file
      command: touch {{file_name}} chdir={{log_dir}} creates={{file_name}}