-
  name: ships setup
  hosts: ships
  tags: ['ship', 'setup']
  vars:
    log_dir: "/target_logs"
    file_name: "{{inventory_hostname}}-ship.txt"
  tasks:
    - name: create ship file
      command: touch {{file_name}}  chdir={{log_dir}} creates={{file_name}}