# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

continuation_prompt = "▶▶"

# Inserts a blank line between shell prompts
add_newline = true
format = "$all$directory$character"

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[docker_context]
format = "via [🐋 $context](blue bold)"

[env_var]
variable = "SHELL"
default = "unknown shell"

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "✓"
untracked = "🤷"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[kubernetes]
disabled = false

[python]
pyenv_version_name = true
version_format = "v${raw}"

[username]
style_user = "white bold"
format = "[$user]($style) "
disabled = false
show_always = true

[shell]
disabled = false
bash_indicator = " 🚀 "

[gcloud]
disabled = true
