version: '3.9'

services:
  target: &target
    privileged: true 
    tty: true   
    scale: 4
    build:
      context: .
      dockerfile: Dockerfile    
    
    security_opt:
      - seccomp:unconfined

    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp:/tmp
      - /run:/run
      - /run/lock:/run/lock

    command: /bin/bash -c "/usr/sbin/init" 
